color: null
fieldLayouts:
  5dd5e2dd-0db5-469d-8db9-a182290f88d6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-24T20:59:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: da20dd65-7a00-4847-a8e3-a9aed580db55
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5bc78c10-aebb-4449-8d83-58b05d645253
        userCondition: null
handle: homepage
hasTitleField: true
icon: ''
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
