color: blue
fieldLayouts:
  6104a56a-762e-4da1-9546-1e40b60bdc3a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-25T08:00:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 84bdbcf1-c225-4a09-89e9-14a346676e72
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-25T08:05:01+00:00'
            elementCondition: null
            fieldUid: 122ccab7-faba-4bd6-ade6-d9f5a4cc307b # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d42365a-b6cc-4efa-9e21-75d0485f4e2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-25T09:41:20+00:00'
            elementCondition: null
            fieldUid: eba9d875-d930-4e6a-aa58-de4497f6fb96 # Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e135c047-9b8d-4aa0-990f-1bc9a5bf96c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-25T08:17:48+00:00'
            elementCondition: null
            fieldUid: e4262ebf-16b4-48e0-b742-08389f3b4024 # Padding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5c64962-e6a2-4fe2-89dc-08babd909c58
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3b77598-e466-4aea-8141-ac5ccb36f268
        userCondition: null
handle: richText
hasTitleField: true
icon: text
name: 'Rich Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
