altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  786f8719-4a80-4352-aa13-34232be85c35:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-25T00:27:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ec0cbc02-7b53-4318-9214-fa84d1e25efb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 14bb8c37-3a51-48bc-a8e8-1512929ee687
        userCondition: null
fs: uploads
handle: assets
name: Assets
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
