columnSuffix: null
handle: reverseLayout
instructions: null
name: 'Reverse Layout'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
