defaultPlacement: end
fieldLayouts:
  748548f5-00b4-4987-be07-2b2598644de1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-25T06:05:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: e7b9718d-06ed-4fd6-9b2b-e83cd6c13d99
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54210258-00be-4d54-bf6e-ec7d2ad50070
        userCondition: null
handle: news
name: News
siteSettings:
  1b2cf952-a9ed-486a-8dd8-be74115414cf: # Craft Site
    hasUrls: true
    template: news/_category.twig
    uriFormat: 'news/{slug}'
structure:
  maxLevels: null
  uid: 278bf2a3-008a-417a-a521-3c0a76c7cf6a
